apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mvp-test-component
  namespace: mvp-demo-dev-namespace-ivdp-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:27dff0ff5ad8fc258ea88cd3203f7e6da29c0e5e84b2fb001d5bc21cf396ef5e
        name: container-image
        resources: {}
status: {}
